### ISSUE TITLE
linear magnification and maybe anisotropic minification?

### ISSUE THREAD

**Issue by WhiteMagicRaven** [bsnes-emu/bsnes#12]
Hello i am new here but i am just in huge love on HD Mode 7 =)
And i am dream to see texture filtration to be implemented 
something like this
https://www.youtube.com/watch?v=E6ut__me_FI
it uses my custom shader for reshade, you can get it here (i know it not perfect, maybe some one can improve it)
http://raven-05.narod.ru/reshade/temp3.fx

**Comment by DerKoun** [comment]
Hi, This is Derkoun, of [bsnes-hd](https://github.com/DerKoun/bsnes-hd). 
HD Mode 7 currently dose not use 3D hardware. So there are no texture filtering options. 
When I get back to working on bsnes-hd (hopefully soon) I have some other things to do, especially performance optimizations. But after that I have a fork with Vulkan/OpenGL support on the top of my list, as it would improve both performance and quality, including options for anisotropic filtering. However, I will need help from someone experienced with those graphics APIs, as I already came into this with little-to-no C++ skills, and learning 3D graphics on top of that is something I doubt I'll manage...

**Comment by WhiteMagicRaven** [comment]
Hello, understand, i have very minimalistic OpenGL and Direct3D knowledges, so i can't be helpful ((( here, maybe some helpers come, i don't know any for just now(
maybe Yaba Sanshiro developers can be helpful in future if they decided to implement hardware acceleration . Just for now two emulators Bsnes and Yaba Sanshiro have similar approach on my opinion =)

**Comment by WhiteMagicRaven** [comment]
https://github.com/mgba-emu/mgba/issues/1748

**Comment by Screwtapello** [comment]
I assume "linear magnification and anisotropic minification" are what graphics APIs typically call bilinear filtering and anisotropic filtering. These operations are built into 3D graphics hardware, and if you have a textured rectangle, it's fairly easy to draw it in 3D and let the GPU do the filtering for you.

It's quite difficult for bsnes because SNES games don't draw "a textured rectangle", they draw ~240 textured rectangles the width of the screen and one scanline high, and bsnes has compare them all and guess (a) are these all part of the same shape, and (b) if so, what was it *supposed* to look like? For some games (like F-Zero) it does indeed turn out to be a textured rectangle, but often it's not. For example, Mario Kart often shows two different views in the top and bottom halves of the screen, there's some tennis game that uses the same background for the horizontal surface of the court and the vertical bleachers behind it, and Terranigma does a weird curvy thing that's not *any* simple shape.

And even if bsnes *could* reliably guess the size, shape and orientation of the original textured quad, implementing those texture filters in software would be a chore, and extracting the texture to render it on the GPU would be even more of a chore.

I'm afraid I'm going to mark this "wontfix" - although I'd actually like to see it happen, realistically there's no chance anyone will have the time and energy to make this happen. If somebody *does* show up, great, but I'm not holding my breath.

**Comment by DerKoun** [comment]
GPU based rendering for Mode 7 scenes that simulate simple perspectives (no curving and so on) is on my to-do list for the long term. There is much to prepare first and I will need help with the GPU stuff, plus I first have to get back to working on bsnes-hd at all. So we will get there... eventually
