### ISSUE TITLE
Add compatibility for expanded Cx4 ROMs

### ISSUE THREAD

**Issue by cascardian** [bsnes-emu/bsnes#17]
I believe this would now be in bsnes' purview as a compatibility hack.

It's a known issue ([MMX3 Zero Project blackscreening](https://www.romhacking.net/forum/index.php?topic=11130.msg382411#msg382411)). The [expanded relocalisation hack by Solid One](https://www.romhacking.net/hacks/5060/) also softlocks during the intro.

**Comment by Screwtapello** [comment]
The MMX3 Zero Project is apparently now available on GitHub: https://github.com/justin3009/MMX3-ZeroProject

I understand that this romhack is using a board configuration not used by any commercial games, and which may(?) not be physically possible with a real Cx4 chip.

To figure out what to do here, I'll need to know:

- how the Cx4 chip actually physically connects to ROM storage, and whatever size limits that implies
- how closely bsnes' current Cx4 implementation adheres to those limits (does it match them exactly? does it enforce a lower limit because that's all MMX2 and MMX3 needed?)
- what limits this romhack actually requires (bigger that bsnes' current limits? bigger than the physical limits?)
- how this romhack tries to communicate with the emulator what it actually needs, in emulators that don't support a manifest or something equivalent

I don't necessarily expect any one person to answer all those questions, probably different people are best positioned to answer different questions. But either I'll need to do all that research, or somebody else will need to do the research and explain it to me before anything else happens.

cc @justin3009 in case they can/want to provide any insight.

**Comment by justin3009** [comment]
It's possible to play it on bsnes as long as a manifest is setup for it. Pretty sure I include the manifest in the source.

**Comment by Screwtapello** [comment]
Ah, right, [this one](https://github.com/justin3009/MMX3-ZeroProject/blob/5e021f446161bc4cc27550162cd0617d4eede63f/Mega%20Man%20X3%20(Manifest%20for%20BSNES)%20%5BRENAME%20TO%20ROM%20NAME%20IN%20ROM%20FOLDER%5D.xml). I need to figure out how to convert the old XML manifests to the new BML format that modern bsnes releases use, but if it the XML manifest works for old bsnes versions, I don't think there's any emulation changes needed  for modern bsnes. The expanded relocalisation romhack was also done by justin3009, so I assume it's the same deal and no emulation changes are required, just a manifest. Feel free to re-open this issue if that's incorrect, or open another one if you have some other question or suggestion.

Thanks for the heads-up, justin3009!
