### ISSUE TITLE
History of BSNES?

### ISSUE THREAD

**Issue by qwertie** [bsnes-emu/bsnes#189]
I'm curious ([for reasons](https://games.slashdot.org/story/21/06/28/2047247/near-creator-of-the-higan-and-bsnes-emulators-has-died))... what is the history of this project? Has Near worked on it recently?

**Comment by Screwtapello** [comment]
Near stepped away from public development in early 2020, so he hasn't personally worked on it recently. Since then, I think some of his private development efforts have made their way into bsnes and higan, but his intention was that bsnes and higan would be 100% in the control of the community... and now that is sadly more true than ever.
