### ISSUE TITLE
Create website and update the about box URL

### ISSUE THREAD

**Issue by byuu** [bsnes-emu/bsnes#2]
It's very important to put together an official website for bsnes, with features, screenshots, and download links. It could also prove helpful to include documentation for bsnes on said page at some point.

bsnes has a URL in the about box which points to the bsnes-emu GitHub repository. It should be updated to point at the new webpage once this is done.

**Comment by Kawa-oneechan** [comment]
(do not whoop your hand up do not *do not* **do not**)

**Comment by Marat-Tanalin** [comment]
[GitHub pages](https://pages.github.com/) could be used for hosting.

**Comment by byuu** [comment]
Absolutely, that is how SameBoy does it. And if someone wants domains to redirect at the GitHub pages, I will pay for 10-year domain registrations for these projects. Just let me know which domains are desired, and where they should point to.

**Comment by victorgoya** [comment]
Please let me know if you need any help on it, I can make a pull request with something clean and responsive using Github Pages and Jekyll, at least to act as a starting point.

**Comment by ChazSII** [comment]
Here's a rough first draft of a static site using GitHub pages and Jekyll (great minds think alike @victorgoya ):

https://chazsii.github.io/bsnes/

It uses Bootstrap and Jquery for responsive design.

Content is a mix of Markdown and Html

I added custom colors to the Cyan, Red, Yellow, and Green Bootstrap SASS variables to match colors extracted from the logo image.

Let me know what you think, if nothing else it could be a starting point for something!

**Comment by RokkumanX** [comment]
@ChazSII 

It's a mystery why no one haven't commented or given you feedback on this, it looks great honestly!

Why is it that most of GitHub issues is dead? Seriously why?

**Comment by merwok** [comment]
@Screwtapello FYI this ticket was closed by a commit that does not seem related.

**Comment by Screwtapello** [comment]
Oops! Thanks!

**Comment by Screwtapello** [comment]
I don't know if this was true when this issue was opened (sorry for the delay, folks!) but bsnes has an "official" URL at https://byuu.org/bsnes/ and the About box URL should be made to point there.

That said, the bsnes web page is currently very bare bones, and while I think it has most of the *content* needed (there's screenshots, there's a feature list, there's links to releases, the repo, the forum, and the Discord) it could probably be organised more attractively. Probably a redesigned web page should match the higan web page, and *that* process depends on choosing new names for the higan UIs. I've filed https://github.com/byuu/byuu.org/issues/9 for that.
