### ISSUE TITLE
DX11 Support / XAudio Update / Xinput

### ISSUE THREAD

**Issue by IPeluchito** [bsnes-emu/bsnes#31]
Please update the drivers to more modern versions, the ones included in the emulator are outdated .... mainly **DX9-> DX11**, **XAudio2.1-> Newer Version** and **Xinput**

**God bless you...**

**Comment by Screwtapello** [comment]
Are these older versions causing you problems? If so, what?

**Comment by IPeluchito** [comment]
Not really, I just think that since you have the base ready, the next step would be to improve performance, modify the emulated hardware and include support for new technologies **(DX11, Vulkan, etc.)** as other **"New Generation"** emulators are doing. ....

Well that's it, I apologize if anyone was offended ...

**God bless you...**

**Comment by Screwtapello** [comment]
Emulators for 3D consoles might benefit from new technologies because those consoles' graphics work quite differently from OpenGL and DX9, and the increased flexibility in Vulkan and DX11 can make it easier to implement.

bsnes does not use OpenGL or DX9 for anything beyond drawing two textured triangles, sixty times a second. DirectX1 would probably be overkill, nevermind DirectX 9.

Likewise, newer versions of XAudio and XInput don't provide anything bsnes could realistically use. bsnes will probably need to be updated to use newer APIs eventually, when the current ones finally stop working, but I think that's still a long way off.
