### ISSUE TITLE
Feature Request: HLE for SuperFX (3d calls using modern APIs)

### ISSUE THREAD

**Issue by vitamingum** [bsnes-emu/bsnes#335]
if the superFX drawing routines were replaced with Direct3D API calls, the games could be rendered at a much higher resolution with proper antialiasing

**Comment by Screwtapello** [comment]
Modern 3D APIs are based around drawing triangles - you tell the GPU where the triangle's corners are, you give it a texture, and the GPU hardware figures out how to draw it at whatever resolution you specify.

The PS1 and N64 have GPUs that are ridiculously primitive compared to modern PC (or even phone) GPUs, but they work on basically the same principle - you tell them where the triangle's corners are, you give them a texture, and the GPU hardware figures out how to draw it. As a result, it's pretty straight forward for a PS1 or N64 emulator to take the triangles the game gives to the emulated GPU, and just pass them along to the real GPU, and get high-resolution output.

The SuperFX works differently. It does not know how to draw triangles. The only thing it knows how to draw is a single pixel. Every game that uses the SuperFX includes its own unique code for deciding when and where to draw pixels - StarFox uses it for 3D vector graphics, Yoshi's Island uses it for 2D graphics, DOOM something else entirely.

The N64 and GameCube are a *little* bit like this because they allow games to upload custom firmware to the GPU, but in the vast majority of cases games used the default firmware that came with the devkit, so you can HLE that and get nice results on most games (and fail horribly on everything else). However, I don't think there's a "default" firmware for the SuperFX, every game does things differently.

So you could HLE StarFox, but that wouldn't help with Yoshi's Island. You could HLE Yoshi's Island, but that wouldn't help with DOOM, etc. I'm sure there are decompilation projects for various SuperFX games which would help figure out how their 3D engines work, and might make it easier to port them to use a native 3D API, but that's not really something appropriate for bsnes.

**Comment by Kawa-oneechan** [comment]
Also, the SuperFX doesn't draw pixels on the screen. It draws pixels to an internal buffer in tge same format as regular tiles which can then be copied into VRAM for display. Meaning it's still beholden to the regular graphics limitations of the SNES.

In contrast, high resolution windowing effects can work because they don't involve actual graphics data at all, and high resolution Mode 7 uses only what graphics data is already there without "creating" anything new. Completely different can of sauce.
