### ISSUE TITLE
Auto region select not work in native open file dialog

### ISSUE THREAD

**Issue by garmendes** [bsnes-emu/bsnes#44]
Works on Snes9x.

![image](https://user-images.githubusercontent.com/22453509/86163042-18d3ce80-bae6-11ea-8c76-6ebf19209886.png)

**Comment by garmendes** [comment]
All versions seems to be affected.

**Comment by Max833** [comment]
Every version in the no-intro romset is working.

Terranigma (Europe).zip
Terranigma (France).zip
Terranigma (Germany) (Rev 1)
Terranigma (Germany)
Terranigma (Spain)

Edit: I find Terranigma (F) as well. No problems. Did you change some compatibility/enhancements settings?

![image](https://user-images.githubusercontent.com/53529402/86184279-2617aa00-bb34-11ea-8b38-1a439f5cdcab.png)

**Comment by garmendes** [comment]
Yes and no. I am using the native file open for selecting roms (it's faster), so this options isn't present and apparently is not on auto with the native open dialog.

**Comment by Max833** [comment]
You are right. It doesn't work with the native file dialogs. It always chooses NTSC. This needs to be fixed.

Well, at least you know how to play the game.

**Comment by Max833** [comment]
bsnes-mt fixed this recently. Maybe this helps bsnes as well: https://github.com/Marat-Tanalin/bsnes-mt/commit/487a84906697c116a523a09034db790f1881925e

**Comment by Screwtapello** [comment]
This is definitely a problem with the native file dialog.

When opening a game with the custom file dialog, the "recent games" entry in `settings.bml` looks like:

    Auto;/path/to/game.sfc

When opening a game with the native file dialog, the entry looks like this:

    ;/path/to/game.sfc

...that is, the "Auto" is missing from the beginning.

**Comment by Screwtapello** [comment]
When you choose "Load Game" from the menu, you (eventually) wind up in `Program::load()`

https://github.com/bsnes-emu/bsnes/blob/090b79b3be8dff3de5566bcbcbc5675d798d6e79/bsnes/target-bsnes/program/platform.cpp#L97-L120

It sets up a `BrowserDialog` struct, setting the list of options ("Auto", "NTSC", "PAL"), calls `Program::openGame()` on it, then extracts the filename and option the user selected.

https://github.com/bsnes-emu/bsnes/blob/090b79b3be8dff3de5566bcbcbc5675d798d6e79/bsnes/target-bsnes/program/utility.cpp#L1-L12

`Program::openGame()` will call `BrowserDialog::openObject()` as-is if the user has chosen custom file dialogs, otherwise it copies relevant information into a `BrowserWindow` and invokes that instead.

`BrowserDialog::openObject()` calls `_run()` which eventually calls the internal `BrowserDialogWindow::run()`, which contains these lines:

https://github.com/bsnes-emu/bsnes/blob/090b79b3be8dff3de5566bcbcbc5675d798d6e79/hiro/extension/browser-dialog.cpp#L225-L229

...so the act of invoking a `BrowserDialog` (a custom file-picker) winds up making the "option" default to the first item in the option list. `BrowserWindow` (a native file-picker) does not do this, and therefore its "option" never gets set at all, causing these issues.

**Comment by Marat-Tanalin** [comment]
This approach does not help when a game is opened via the “Load Recent Game” list that does not involve file-opening dialog, if the game was originally opened in a previous bsnes version that didn’t yet contain the fix.

The bsnes-mt approach takes this into account by acting on a later stage and treating anything different from `NTSC` and `PAL` as `Auto` regardless of how exactly the game is opened.

**Comment by Screwtapello** [comment]
I made #89 to fix up entries in the Recent Games menu.
