### ISSUE TITLE
Add support for SuperFX ROMs larger than 2MB

### ISSUE THREAD

**Issue by jimmy-ds** [bsnes-emu/bsnes#52]
Hi,

As illustrated in the SNES development manual, the S-CPU should be able to access ROM outside of the first 2MB range on SuperFX carts via banks 80-FF:

![image](https://user-images.githubusercontent.com/69101310/89116692-0e418780-d44c-11ea-86b4-67eaf9d5d1a0.png)

Currently, no emulator supports this feature (as far as I am aware), and although no official SuperFX game utilizes this memory region, I believe the addition of this feature would greatly benefit the homebrew and ROM hacking community.

Thanks!

**Comment by Screwtapello** [comment]
The SuperFX chip has a ROMB register, which controls what ROM bank the SuperFX chip reads from. bsnes [specifically limits it to a 7-bit value](https://github.com/bsnes-emu/bsnes/blob/968e6b5feba363ced6b291a13036d1803cd1f39a/bsnes/processor/gsu/instructions.cpp#L378), so it can never refer to banks 80-FF. A SNES programming book I found [documents it as a 7-bit register](https://en.wikibooks.org/wiki/Super_NES_Programming/Super_FX_tutorial#ROMBR_Game_Pak_ROM_Bank_Register). Nocash's fullsnes doc straight up says ROMB can be set "only to ROM region (00h-5Fh)" which is even more restrictive, but exactly lines up with the "GAME PAK ROM IMAGE" regions of your diagram.

However, that's just ROM that the SuperFX can access. The ordinary SNES CPU can still access the whole memory map, and I think in theory if a cartridge had an extra ROM chip wired up directly to the address bus (instead of behind the SuperFX) in banks 80-FF, I expect the CPU could access those.

The circuit board definition for Star Fox (to pick a simple SuperFX game) looks like this:

https://github.com/bsnes-emu/bsnes/blob/968e6b5feba363ced6b291a13036d1803cd1f39a/bsnes/target-bsnes/resource/system/boards.bml#L192-L198

As you can see, the Program ROM and Save RAM are "behind" the GSU processor, which means they're subject to the GSU's 7-bit ROMB limit. However, you could add another block of Program ROM beside the GSU processor:

```
board: fictional-expanded-superfx-board
  processor architecture=GSU
    map address=00-3f,80-bf:3000-34ff
    memory type=ROM content=Program
      map address=00-1f,80-9f:8000-ffff mask=0x8000
    memory type=RAM content=Save
      map address=60-7d,e0-ff:0000-ffff
  memory type=ROM content=Program
    map address=80-bf:8000-ffff mask=0x8000
    map address=c0-ff:0000-ffff
```

That would give you more ROM space for the SNES CPU to use, although I'm not sure what would happen if the SuperFX and the CPU tried to access different memory addresses at the same time. Bad things, probably.

At any rate, I expect bsnes already supports SuperFX ROMs larger than 2MB about as well as real hardware possibly could, so I'm going to close this issue.

If a custom manifest like the above doesn't work in bsnes, that might be a bug of its own (I'm not sure exactly how flexible the manifest system is expected to be yet), that should be filed separately.

On the other hand, if people want bsnes to emulate a fictional variant of the SuperFX chip with an 8-bit ROMB register, that would be another, different issue. I'm not wholly opposed to the idea if other emulators and the FXPAK Pro support it (see: MSU-1), but I'm not very interested in emulating fantasy hardware.
