### ISSUE TITLE
Sub-frame rendering?

### ISSUE THREAD

**Issue by UNHchabo** [bsnes-emu/bsnes#56]
I'm mostly just curious, but I suppose this idea would reduce input lag that tiny bit more...

Could we take advantage of high-refresh monitors by drawing at more than 60fps? It seems like the newly-calculated scanlines could be updated 4 times per frame on a 240Hz monitor, for instance.

**Comment by birdybro** [comment]
I was under the assumption the hard problem of input latency in emulation is mostly because of the buffer associated with having cycle timing being emulated in software. Run-ahead latency reduces latency significantly but can often introduce bugs, but this is because it's running a sort of simulation of future possibilities (if you press a button given the situation, and it gives you that path instead of reacting in the emulator's version of the system).

**Comment by Screwtapello** [comment]
In theory, yeah, drawing twice per frame on a 120Hz display, or four times per frame on a 240Hz display would lower display lag. However, I believe bsnes' current architecture is fundamentally built on the cycle of (a) emulate the SNES for an entire frame, (b) do all the house-keeping of responding to GUI events, providing video and audio data to the OS, (c) repeat. Reworking everything to handle partial-frame updates sounds like a *lot* of work, and I don't think it'll be practical to make such a significant change any time soon.

If somebody really wants to try it out, they're welcome to, and we may revisit this decision in the future, but for the moment  I'm going close this as WONTFIX.
