### ISSUE TITLE
Suggestion to port to from QT4 to QT5

### ISSUE THREAD

**Issue by birdybro** [bsnes-emu/bsnes#65]
QT4 has been EOL since December 2015, so basically 5 years now. Porting to QT5 should be a priority at some point as newer versions of both windows and linux distros could potentially (unlikely soon however) break functionality of the UI suddenly.

**Comment by Screwtapello** [comment]
There's [already](https://github.com/bsnes-emu/bsnes/blob/master/hiro/GNUmakefile#L54-L58) a Qt5 port, just add `hiro=qt5` to the command-line instead of `hiro=qt4` when building:

    make -C bsnes hiro=qt5

The Qt5 port may not be as polished or well-tested as the Qt4 port; if you encounter any problems please file issues about them, or if you can figure out how to fix them that would be even better.
