### ISSUE TITLE
Help > Documentation leads to a 404 page

### ISSUE THREAD

**Issue by FMecha** [bsnes-emu/bsnes#73]
Going to Help > Documentation links to https://byuu.org/doc/bsnes, which throws a 404 page, as of version 115.

**Comment by Screwtapello** [comment]
Apparently that URL was added to bsnes after v113, and removed after v115. But, since v115 is the latest official version and probably will be for a while longer, we should make it not a 404.

https://github.com/byuu/byuu.org/pull/7/commits/1d52bb15ec6d76d43c2b725c469d2c84b078ed2b

Thanks for reporting the issue!
