### ISSUE TITLE
Disable screensaver while playing on macOS

### ISSUE THREAD

**Issue by asheenlevrai** [bsnes-emu/bsnes#87]
Hi 😊
I'm using the current nightly on macOS Catalina.
how do I prevent screensaver (or monitor /computer sleep) from messing up with game play?
Thanks
-a-

**Comment by Kawa-oneechan** [comment]
I recall Byuu talking about how his UI would not likely support screensaver suppression because every single supported OS has its own ways of doing so. I'd imagine for certain OSes newer versions might even not support the same suppression method as older versions of the very same OS.

If I remember correctly, it's mostly because the OS' own screensaver suppression only considers the keyboard and mouse, so if you play for an extended time on a controller, it'll think you're not actually doing anything at all and go to sleep/turn on the screensaver.

Considering the first paragraph, that leaves you with two options: don't play on a controller, or disable/extend the sleep timer.

(Full disclosure, I know jack shit about Catalina.)

**Comment by asheenlevrai** [comment]
Oh... bummer.
OK, thanks for the heads up :)

**Comment by Screwtapello** [comment]
If there's a way to automatically disable the screensaver while playing a game on macOS, and it's easy to integrate it into bsnes, that would be a great feature to have. Sadly, I don't personally know anything about macOS so I'm hoping somebody with that knowledge wanders by and is interested in contributing.
