### ISSUE TITLE
Actraiser input desynchronization

### ISSUE THREAD

**Issue by Reinc01** [bsnes-emu/bsnes#94]
I recorded a playthrough of the SNES game Actraiser, but the input movie desynchronizes. I used the BSNES core of Bizhawk emulator for recording.
[ActRaiser (USA).zip](https://github.com/bsnes-emu/bsnes/files/5491050/ActRaiser.USA.zip)

**Comment by Screwtapello** [comment]
Please don't attach copyrighted content to the issue-tracker, you'll get us in trouble. Just mention the MD5 or SHA1 hash of the game you're talking about, and we should be able to figure it out.

I don't think BizHawk uses the latest version of bsnes for its SNES emulation, I think they have an older version that they've patched to their liking. If Actraiser desyncs in BizHawk, they would probably know a lot more about it than we would, especially since Actraiser is a pretty popular game. I recommend you ask the Bizhawk people first, and if they decide they need to change their SNES core to fix the problem, maybe we can apply the fix too.

Nevertheless, thank you for taking the time to report an issue!

**Comment by Reinc01** [comment]
What copyrighted content did I attach? The .zip file contains the input movie, not the ROM.

**Comment by Screwtapello** [comment]
Oh, sorry, I assumed it was the ROM, and I didn't want to download it in case it was.
